### ISSUE TITLE
移动端没有侧边栏，手机上的侧边栏点击无效。

### ISSUE THREAD

**Issue by zisen123** [bmqy/bmqy-next#1]
如题，分别使用iPad和一部Android手机进行测试。手机能显示侧边栏按钮但是点击无效果，iPad端不显示按钮。
请求切换到桌面版网站之后两部设备均看不到侧边栏按钮。

**Comment by bmqy** [comment]
> 如题，分别使用iPad和一部Android手机进行测试。手机能显示侧边栏按钮但是点击无效果，iPad端不显示按钮。
> 请求切换到桌面版网站之后两部设备均看不到侧边栏按钮。

是有的，请在看一下，在左上角，三横杠的图标
