### ISSUE TITLE
设置顶部不显示

### ISSUE THREAD

**Issue by ahaolee** [bmqy/bmqy-next#2]
访问作者你的博客看到你的博客顶部可以显示图像，但是我在主题自定义设置中设置了顶部图像却不显示。请问能否解答？

**Comment by bmqy** [comment]
> 访问作者你的博客看到你的博客顶部可以显示图像，但是我在主题自定义设置中设置了顶部图像却不显示。请问能否解答？

提供下网址，我看下，应该是设置好就可以了，强制刷新看下

**Comment by ahaolee** [comment]
谢谢，设置了就可以了。------------------ 原始邮件 ------------------发件人: 北门清燕  <notifications@github.com>发送时间: 2019年10月15日 11:55收件人: bmqy/bmqy-next <bmqy-next@noreply.github.com>抄送: ahaoLee <1818mini520@gmail.com>, Author <author@noreply.github.com>主题: 回复：[bmqy/bmqy-next] 设置顶部不显示 (#2)
访问作者你的博客看到你的博客顶部可以显示图像，但是我在主题自定义设置中设置了顶部图像却不显示。请问能否解答？

提供下网址，我看下，应该是设置好就可以了，强制刷新看下

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bmqy/bmqy-next/issues/2?email_source=notifications\u0026email_token=AIQHJBUYAT4D5RAM6CESDCTQOU5MVA5CNFSM4IUPFW6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBHKKKA#issuecomment-542025000",
"url": "https://github.com/bmqy/bmqy-next/issues/2?email_source=notifications\u0026email_token=AIQHJBUYAT4D5RAM6CESDCTQOU5MVA5CNFSM4IUPFW6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBHKKKA#issuecomment-542025000",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bmqy** [comment]
好的
